name: Generate betterproto stubs

on:
  push:
    branches: [ main ]
    paths:
      - 'proto/**/*.proto'
      - '.github/workflows/generate-python-betterproto.yml'
  pull_request:
    paths:
      - 'proto/**/*.proto'
      - '.github/workflows/generate-python-betterproto.yml'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        run: pip install uv

      - name: Set up venv and install betterproto
        run: |
          uv venv .venv
          source .venv/bin/activate
          uv pip install betterproto

      - name: Generate betterproto stubs
        run: |
          source .venv/bin/activate
          mkdir -p telegram-bot/proto_stubs
          .venv/bin/betterproto --python_out=telegram-bot/proto_stubs proto/*.proto

      - name: Ensure __init__.py exists
        run: |
          touch telegram-bot/__init__.py
          touch telegram-bot/proto_stubs/__init__.py

      - name: Upload generated bindings
        uses: actions/upload-artifact@v4
        with:
          name: python-proto-bindings
          path: telegram-bot/proto_stubs